# Generated by Django 5.0.6 on 2024-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZohoFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.CharField(blank=True, max_length=255, null=True)),
                ("field2", models.CharField(blank=True, max_length=255, null=True)),
                ("field3", models.CharField(blank=True, max_length=255, null=True)),
                ("field4", models.CharField(blank=True, max_length=255, null=True)),
                ("field5", models.CharField(blank=True, max_length=255, null=True)),
                ("field6", models.CharField(blank=True, max_length=255, null=True)),
                ("field7", models.CharField(blank=True, max_length=255, null=True)),
                ("field8", models.CharField(blank=True, max_length=255, null=True)),
                ("field9", models.CharField(blank=True, max_length=255, null=True)),
                ("field10", models.CharField(blank=True, max_length=255, null=True)),
                ("field11", models.CharField(blank=True, max_length=255, null=True)),
                ("field12", models.CharField(blank=True, max_length=255, null=True)),
                ("field13", models.CharField(blank=True, max_length=255, null=True)),
                ("field14", models.CharField(blank=True, max_length=255, null=True)),
                ("field15", models.CharField(blank=True, max_length=255, null=True)),
                ("field16", models.CharField(blank=True, max_length=255, null=True)),
                ("field17", models.CharField(blank=True, max_length=255, null=True)),
                ("field18", models.CharField(blank=True, max_length=255, null=True)),
                ("field19", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
